### ISSUE TITLE
How incomplete is this?

### ISSUE THREAD

**Issue by Lambda-Epsilon** [Mathiaszero/Roblox-Survival_303_2012-abandoned#1]

**Comment by Mathiaszero** [comment]
Did you used to play this game? This is merely a download from the game page as I had not looked at this for many years. If I can recall it should still have a map, but not sure if there any scripts.   So it is very incomplete since it runs on an older version of Roblox Studio.  I don't know if it can even still open on the current Studio version.  If you want a later version, go to https://www.roblox.com/games/3011874593/Survival-303-Classic-FE and click the 3 dots next to title.

**Comment by Lambda-Epsilon** [comment]
Sounds good, thanks!
